In [21]:
import pickle
with open('2912995.pkl', 'rb') as f:
    data_new = pickle.load(f)

In [22]:
data_new

        id        time state message_from_u         meassage_to_u    target_id
0  2912995  1569143462     0                                               NaN
0  2912995  1569143462     1         привет         Базовое меню.          NaN
0  2912995  1569143464   2_1  Для отношений  Рекомендация Девушки          NaN
0  2912995  1569143467   2_1       Нравится              Нравится   17526561.0
0  2912995  1569143469   2_1       Нравится              Нравится  172506407.0
0  2912995  1569143470   2_1    Не нравится           Не_нравится    7119571.0
0  2912995  1569143472   2_1    Не нравится           Не_нравится  139625701.0
0  2912995  1569143475   2_1    Не нравится           Не_нравится  249667624.0
0  2912995  1569143476     1          Назад         Базовое меню.          NaN